name: Scheduled healthcheck

on:
  schedule:
    - cron: '* 0 * * *'

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: check the deployed app url
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://fso-pokedex.herokuapp.com/